name: CI

on: [push, pull_request]

jobs:
  golang:
    name: Build and test cboring

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.22' ]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build on Go ${{ matrix.go }}
      run: go build ./...

    - name: Test
      run: go test -v -rapid.checks=10_000 ./...
